apiVersion: v1
kind: Service
metadata:
    name: my-nginx-service
spec:
    type: NodePort
    ports:
        - port: 80
          nodePort: 30123
          targetPort: 9376
    selector:
        app: nginx